
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.baza_wiedzyDeps.db.deployment.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.baza_wiedzyDeps.db.deployment.name }}
spec:
  progressDeadlineSeconds: 200
  replicas: {{ .Values.baza_wiedzyDeps.db.deployment.replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ .Values.baza_wiedzyDeps.db.deployment.name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.baza_wiedzyDeps.db.deployment.name }}
    spec:
      containers:
        - name: {{ .Values.baza_wiedzyDeps.db.deployment.name }}
          image: "{{ .Values.baza_wiedzyDeps.db.deployment.image }}:{{ .Values.baza_wiedzyDeps.db.deployment.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.baza_wiedzyDeps.db.deployment.port }}
          resources:
            limits:
              cpu: "{{ .Values.baza_wiedzyDeps.db.deployment.limits.cpu }}"
              memory: "{{ .Values.baza_wiedzyDeps.db.deployment.limits.memory }}"
            requests:
              cpu: "{{ .Values.baza_wiedzyDeps.db.deployment.requests.cpu }}"
              memory: "{{ .Values.baza_wiedzyDeps.db.deployment.requests.memory }}"
          volumeMounts:
            - mountPath: "/data/db"
              name: {{ .Values.baza_wiedzyDeps.db.pvc.name }}
            - mountPath: "/dev/shm"
              name: shm
          env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.baza_wiedzyDeps.db.auth.initRootPassword }}
                  key: MONGO_PASSWORD
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.baza_wiedzyDeps.db.auth.initRootUsername }}
                  key: MONGO_USER
            - name: MONGO_INITDB_DATABASE
              value: baza_wiedzy
            - name: GLIBC_TUNABLES
              value: "glibc.pthread.rseq"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 60
      volumes:
        - name: {{ .Values.baza_wiedzyDeps.db.pvc.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.baza_wiedzyDeps.db.pvc.name }}
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 512Mi
