apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.baza_wiedzyDeps.db.pv.name }}
spec:
  storageClassName: ""
  capacity:
    storage: {{ .Values.baza_wiedzyDeps.db.pv.storage }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.baza_wiedzyDeps.db.pv.hostPath }}
