apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongo-secret
  namespace: { { .Values.namespace } }
spec:
  encryptedData:
    MONGO_PASSWORD: AgC8iNoUtmE8N9+6ZZkd5zHSR5sOA4e4lmATq9S+Ny8VeW0XFpgaDbx+/i9fndH8vDaFWzk3DxPReppT2/W30Ly3HqbqoDBoj6xRh8JmEy3T1KU1Stfke5u2j2pafD/kqYYMtoJYpwbSrCJmGtPcyzwCkBpIYFduLAovABzmxegrNC7vwxTHZ1sGS3rxxuD+YUpMkkle96kM99BqQ8t/8b97CJotWYFDt1Dg8W8phlW5xmBsovsOoTWFlhJ4Wf1QM7wmucWDhdqzQw1c40VPaTOguJNo0o6amz3X+XaUXlFr3cN+ibaeNie46fQmW16f5HrPOaFPcbLq0VsnLdEG9SPuy+3aom30rTwqKrKjVskICFxDqRFy9oe6HeQ+7wVYNj6xIghiyBE52PiImlj+mJ32N3lRxnaq0KcgXuUEBYzvCsmER62lNOEojvTDQQq+sS2P2vVRKXXEdvZCmeHrg1KrXRstsp2/8BXGYPePw9DEGaSS/N0vPBf5OvBdHvmnPOjdZWVVFnDvAdKeNShwaWoazA5DEzq+26EoQKWkWrycwg1HCGDRblxxM/DjBdXHskG8mVweJo+El47pHSfeP58WILJT6t6J1G8Z8fKF5D4tPpf15YDDWIMuzlxakIoCGJjJgX+LtHNILzovMrDW/p5XGlHfFIjMZBdjTlk1//z5wCH/XRmEAaeRIwhvZHcd2NdU0k0SjbZhdGLL+PV7mcY6Qf9eCPRimpnRDsKdzTTeoTtRUqgklXflxCCVAWLKeqOZ7A==
    MONGO_USER: AgBb+jbPLvHCpPjsp3VZR4qZRZgr5fSCFhsDMXyMQlJiad/z/axoFOv6edOmKF+oSRxw7OciB3F+bZpm6K6sRr0DWd45eRCU6OFwdsizJsJCLMB7gqVEzF5JO05Swbv+d4dIPE2TpIO8Bfpeir+dATwKHmAD78WLSjhYwQVt1wKBI08qoZhAUnL4Ih9dDEq6VwbZOK3ZdrKJ+SJ/uT6qOjzAMw8hF4d0E8RfPzkaHD5YR0u4aMV5aQX+jObr1vr922ccjzJbxlMvyWA+mc4rvX+Bso62tagbcSe3utKg4HUAZW7QuPJJ3UFP0mYQxxwjPTuYDP6OxjdEXlYfCf4wCzonmggBPrIziGKEKP+oZxgaOFPNuFaYeWC50KTzmU3ySmj2L05EhIUq2qEjqXqaJWpqWjrpkUui5CgKBns+i0mVBOv3Nzy3/KUtGkE0bwl4c+vZWbeJE1jvNJbVPqiJq2Hm0GeGXX2YZF4tSELeZs3OwWkCX/KhXW4lTARc5DR8tkMsRuEVXbNSh5h0FMaYtgP/olB5pO+25B9hkDz0M5J7UYdPZQa88MNVCdv4x8d8gGNbS51LpCDs8W2WOaZuMoRQ/KEXIPqFX1CstjRpQ61uDwN27HSxV6JTwItbD+n7UeBNwpua2IhKEIEYOuQJO7Dw64uW2BCBviSyBs7aHDvWR8O6B4Vg3LuNPbWuyz/R/3Yy909UO4JLDdo=
  template:
    metadata:
      name: mongo-secret
      namespace: { { .Values.namespace } }
    type: Opaque
