apiVersion: v1
kind: Service
metadata:
  name: { { .Values.baza_wiedzyDeps.db.service.name } }
  namespace: { { .Values.namespace } }
spec:
  selector:
    app: { { .Values.baza_wiedzyDeps.db.deployment.name } }
  ports:
    - name: { { .Values.baza_wiedzyDeps.db.service.port.name } }
      protocol: TCP
      port: { { .Values.baza_wiedzyDeps.db.deployment.port } }
      targetPort: { { .Values.baza_wiedzyDeps.db.service.port.value } }
