apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.forgejoDeps.navidrome.deployment.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.forgejoDeps.navidrome.deployment.name }}
spec:
  progressDeadlineSeconds: 200
  replicas: {{ .Values.forgejoDeps.navidrome.deployment.replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ .Values.forgejoDeps.navidrome.deployment.name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.forgejoDeps.navidrome.deployment.name }}
    spec:
      containers:
      - name: {{ .Values.forgejoDeps.navidrome.deployment.name }}
        image: "{{ .Values.forgejoDeps.navidrome.deployment.image }}:{{ .Values.forgejoDeps.navidrome.deployment.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.forgejoDeps.navidrome.deployment.port }}
        resources:
          limits:
            cpu: "{{ .Values.forgejoDeps.navidrome.deployment.limits.cpu }}"
            memory: "{{ .Values.forgejoDeps.navidrome.deployment.limits.memory }}"
          requests:
            cpu: "{{ .Values.forgejoDeps.navidrome.deployment.requests.cpu }}"
            memory: "{{ .Values.forgejoDeps.navidrome.deployment.requests.memory }}"
        volumeMounts:
          - name: {{ .Values.forgejoDeps.navidrome.data.pvc.name }}
            mountPath: /data
          - name: {{ .Values.forgejoDeps.navidrome.music.pvc.name }}
            mountPath: /music
        env:
          - name: ND_SCANSCHEDULE
            value: 1h
          - name: ND_LOGLEVEL
            value: info
          - name: ND_SESSIONTIMEOUT
            value: 24h
          - name: ND_ENABLEINSIGHTSCOLLECTOR
            value: "false"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 60
      volumes:
        - name: {{ .Values.forgejoDeps.navidrome.data.pvc.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.forgejoDeps.navidrome.data.pvc.name }}
        - name: {{ .Values.forgejoDeps.navidrome.music.pvc.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.forgejoDeps.navidrome.music.pvc.name }}

