apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.forgejoDeps.navidrome.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.forgejoDeps.navidrome.deployment.name }}
  ports:
    - name: {{ .Values.forgejoDeps.navidrome.service.port.name }}
      protocol: TCP
      port: {{ .Values.forgejoDeps.navidrome.deployment.port }}
      targetPort: {{ .Values.forgejoDeps.navidrome.service.port.value }}
