apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.forgejoDeps.db.pv.name }}
spec:
  storageClassName: ""
  capacity:
    storage: {{ .Values.forgejoDeps.db.pv.storage }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.forgejoDeps.db.pv.hostPath }}
