# Generic
namespace: server-prod

# Application dependencies
baza_wiedzyDeps:
  # Mongo
  db:
    deployment:
      name: baza-wiedzy-db-mongo
      replicas: 1
      image: mongo
      tag: 8.2-noble
      port: 3306
      limits:
        cpu: 1
        memory: 2Gi
      requests:
        cpu: 0.25
        memory: 200M
    pvc:
      name: baza-wiedzy-db-mongo-pvc
      storage: "10Gi"
    pv:
      name: baza-wiedzy-db-mongo-pv
      storage: "10Gi"
      hostPath: /home/jakub/pv/mongo
    auth:
      initRootPassword: mongo-secret
      initRootUsername: mongo-secret
    service:
      name: baza-wiedzy-db-mongo-service
      port:
        name: baza-wiedzy-db-mongo-service-http
        value: 27017
