# Generic
namespace: server-dev

# Application dependencies
baza_wiedzyDeps:
  # Mongo
  db:
    deployment:
      name: baza-wiedzy-db-mongo
      replicas: 1
      image: mongo
      tag: 8.2-noble
      port: 27017
      limits:
        cpu: 1
        memory: 2Gi
      requests:
        cpu: 0.25
        memory: 200M
    pvc:
      name: baza-wiedzy-db-mongo-pvc
      storage: "10Gi"
    pv:
      name: baza-wiedzy-db-mongo-pv
      storage: "10Gi"
      hostPath: /home/jakub/pv/mongo2
    auth:
      initRootPassword: mongo-secret
      initRootUsername: mongo-secret
    service:
      name: baza-wiedzy-db-mongo-service
      port:
        name: baza-wiedzy-db-mongo-service-http
        value: 27017
  # Container registry
  registry:
    deployment:
      name: baza-wiedzy-registry
      replicas: 1
      image: registry
      tag: 3
      port: 5000
      limits:
        cpu: 1
        memory: 2Gi
      requests:
        cpu: 0.25
        memory: 200M
    service:
      name: baza-wiedzy-registry-service
      port:
        name: baza-wiedzy-registry-service-http
        value: 5000

  backend:
    deployment:
      name: baza-wiedzy-backend
      replicas: 1
      image: registry2.kiszczyc.pl/backend
      tag: latest
      port: 5000
      limits:
        cpu: 1
        memory: 2Gi
      requests:
        cpu: 0.25
        memory: 200M
    service:
      name: baza-wiedzy-backend-service
      port:
        name: baza-wiedzy-backend-service-http
        value: 5000
