apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.baza_wiedzyDeps.registry.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: {{ .Values.baza_wiedzyDeps.registry.deployment.name }}
    app.kubernetes.io/name: {{ .Values.baza_wiedzyDeps.registry.deployment.name }}
  ports:
    - name: {{ .Values.baza_wiedzyDeps.registry.service.port.name }}
      port: {{ .Values.baza_wiedzyDeps.registry.deployment.port }}
      targetPort: {{ .Values.baza_wiedzyDeps.registry.service.port.value }}
      nodePort: {{ .Values.baza_wiedzyDeps.registry.service.nodePort.value }}
