apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.baza_wiedzyDeps.backend.deployment.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.baza_wiedzyDeps.backend.deployment.name }}
spec:
  progressDeadlineSeconds: 200
  replicas: {{ .Values.baza_wiedzyDeps.backend.deployment.replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ .Values.baza_wiedzyDeps.backend.deployment.name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.baza_wiedzyDeps.backend.deployment.name }}
    spec:
      containers:
        - name: {{ .Values.baza_wiedzyDeps.backend.deployment.name }}
          image: "{{ .Values.baza_wiedzyDeps.backend.deployment.image }}:{{ .Values.baza_wiedzyDeps.backend.deployment.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.baza_wiedzyDeps.backend.deployment.port }}
          resources:
            limits:
              cpu: "{{ .Values.baza_wiedzyDeps.backend.deployment.limits.cpu }}"
              memory: "{{ .Values.baza_wiedzyDeps.backend.deployment.limits.memory }}"
            requests:
              cpu: "{{ .Values.baza_wiedzyDeps.backend.deployment.requests.cpu }}"
              memory: "{{ .Values.baza_wiedzyDeps.backend.deployment.requests.memory }}"
          volumeMounts:
            - mountPath: "/app/uploads"
              name: {{ .Values.baza_wiedzyDeps.backend.pvc.name }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 60
      volumes:
        - name: {{ .Values.baza_wiedzyDeps.backend.pvc.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.baza_wiedzyDeps.backend.pvc.name }}
