apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.baza_wiedzyDeps.backend.pvc.name }}
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: ""
  volumeName: {{ .Values.baza_wiedzyDeps.backend.pv.name }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.baza_wiedzyDeps.backend.pvc.storage }}
