apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
spec:
  ingressClassName: traefik
  rules:
  - host: bazawiedzy.kiszczyc.pl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bazawiedzy-http
            port:
              number: 5000
  - host: www.bazawiedzy.kiszczyc.pl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bazawiedzy-http
            port:
              number: 5000
