apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
spec:
  buffering:
    maxRequestBodyBytes: 0
    memRequestBodyBytes: 0
    maxResponseBodyBytes: 0
    memResponseBodyBytes: 0
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: https
  ingressClassName: traefik
  rules:
  - host: registry2.kiszczyc.pl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: baza-wiedzy-registry-service
            scheme: http
            port:
              number: 5000
  - host: www.registry2.kiszczyc.pl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: baza-wiedzy-registry-service
            scheme: http
            port:
              number: 5000
